name: Generate Image List

on:
  push:
    paths:
      - 'drawings/**'  # runs only when the drawings folder changes

jobs:
  generate-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Create images.js file
        run: |
          echo "const drawings = [" > images.js
          for img in drawings/*; do
            echo "  'drawings/$img'," >> images.js
          done
          echo "];" >> images.js

      - name: Commit the updated images.js
        run: |
          git config --global user.email "lisadikaprio@gmail.com"
          git config --global user.name "LisadiKaprio"
          git add images.js
          git commit -m "Github Actions: Update image list"
          git push
